In [ ]:
import datetime
import os
import json
import re
from functools import partial
from itertools import count, filterfalse

import numpy as np
import pandas as pd
from sklearn.datasets import fetch_20newsgroups
from gensim.models import word2vec
from sklearn.mixture import GaussianMixture
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
import pandas as pd
from itertools import count


input_train='./aozora_datasets_min/train_author_novel.csv'
df_train = pd.read_csv(input_train)

In [7]:
import glob
import os

import pandas as pd

In [ ]:
train_files = glob.glob('./aozora_datasets_min/train_datasets/*.txt')

In [ ]:
train_files = glob.glob('./aozora_datasets_min/train_datasets/*.txt')
train_filenames = list(map(os.path.basename, train_files)) # doesnt reproduce result when iter is consumed
train_authors = list(map(filename_author_map.get, train_filenames))

In [4]:
input_filepath = './aozora_datasets_min/train_author_novel.csv'

In [5]:
df_train = pd.read_csv(input_filepath)

In [87]:
from itertools import groupby
from oprea

import numpy as np

In [119]:
def stratified_splitter(rng, labels, n_splits=5):
    ordering = labels.argsort()
    u, c = np.unique(labels, return_counts=True)
    train_indices = []
    test_indices = []
    for shuffled_indices in map(rng.permutation, np.split(np.arange(labels.size)[ordering], c[:-1].cumsum())):
        return shuffled_indices
        fold_indices = np.arange(shuffled_indices.size) % n_splits
        for k in np.arange(u.size):
            mask = fold_indices != k
            train_indices.append(shuffled_indices[mask])
            test_indices.append(shuffled_indices[~mask])
    return map(np.concatenate, (train_indices, test_indices))

In [120]:
rng = np.random.RandomState(42)
n_splits = 10

In [122]:
stratified_splitter(rng, labels)

array([1474, 1400, 1533, 1416, 1392, 1463, 1491, 1435, 1500, 1450, 1407,
       1425, 1492, 1430, 1408, 1415, 1527, 1477, 1480, 1388, 1499, 1447,
       1523, 1462, 1532, 1498, 1398, 1497, 1513, 1471, 1423, 1528, 1459,
       1502, 1514, 1429, 1451, 1507, 1383, 1403, 1478, 1396, 1421, 1406,
       1473, 1460, 1395, 1448, 1485, 1496, 1441, 1399, 1529, 1489, 1426,
       1479, 1468, 1397, 1404, 1391, 1461, 1433, 1526, 1505, 1464, 1445,
       1511, 1501, 1449, 1419, 1503, 1506, 1386, 1470, 1401, 1432, 1518,
       1437, 1524, 1522, 1455, 1495, 1380, 1394, 1466, 1420, 1412, 1443,
       1484, 1424, 1393, 1439, 1493, 1402, 1504, 1494, 1521, 1482, 1446,
       1458, 1390, 1413, 1405, 1531, 1422, 1512, 1481, 1476, 1469, 1515,
       1486, 1490, 1472, 1456, 1530, 1483, 1418, 1382, 1487, 1465, 1417,
       1444, 1389, 1440, 1520, 1436, 1519, 1467, 1434, 1453, 1438, 1410,
       1508, 1452, 1431, 1517, 1510, 1427, 1488, 1442, 1516, 1385, 1381,
       1411, 1409, 1454, 1525, 1428, 1509, 1457, 13

In [121]:
train_indices, stratified_splitter(rng, labels)

NameError: name 'train_indices' is not defined

In [95]:
labels = df_train.author_id.values
ordering = labels.argsort()

In [94]:
np.unique(labels, return_counts=True)[1][:-1].cumsum()

array([ 154,  196,  378,  429,  487,  536,  596,  643,  694,  807,  934,
        992, 1032, 1126, 1215, 1531])

In [106]:
np.split(np.arange(labels.size)[ordering], np.unique(labels, return_counts=True)[1][:-1].cumsum())

[array([1391, 1488, 1487, 1486, 1485, 1484, 1483, 1482, 1481, 1480, 1479,
        1478, 1477, 1476, 1475, 1474, 1489, 1490, 1491, 1492, 1509, 1508,
        1507, 1506, 1505, 1503, 1502, 1473, 1501, 1499, 1498, 1497, 1496,
        1495, 1494, 1493, 1500, 1510, 1472, 1470, 1449, 1448, 1447, 1446,
        1445, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442, 1443, 1444,
        1450, 1451, 1452, 1453, 1469, 1468, 1467, 1466, 1465, 1464, 1463,
        1471, 1462, 1460, 1459, 1458, 1457, 1456, 1455, 1454, 1461, 1511,
        1504, 1513, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409,
        1410, 1512, 1412, 1413, 1414, 1415, 1400, 1399, 1398, 1397, 1380,
        1381, 1382, 1383, 1384, 1385, 1386, 1416, 1387, 1389, 1390, 1392,
        1393, 1394, 1395, 1396, 1388, 1417, 1411, 1419, 1528, 1527, 1526,
        1525, 1524, 1418, 1522, 1521, 1520, 1519, 1518, 1517, 1516, 1515,
        1514, 1529, 1530, 1523, 1532, 1420, 1531, 1422, 1423, 1424, 1425,
        1426, 1427, 1421, 1429, 1430, 

In [78]:
u, inv = np.unique(labels, return_inverse=True)

In [85]:
ordering = inv.argsort()

In [86]:
ordering

array([1391, 1488, 1487, ..., 1349, 1347, 1362])

In [81]:
u

array([  50,   52,   82,  146,  153,  162,  270,  281,  305,  908,  933,
       1224, 1373, 1562, 1569, 1670, 1779])

In [82]:
labels

array([162, 162, 162, ..., 153, 153, 153])

In [73]:
u, inv, ind = np.unique(labels, return_index=True, return_inverse=True)

In [74]:
ind[inv.argsort()]

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [75]:
inv

array([1380,  144,   49,  753,  979,    0,  804,  705,  187,  866,  864,
        240,  981,   50,  616,  299,  332])

In [64]:
inv

array([5, 5, 5, ..., 4, 4, 4])

In [65]:
u

array([  50,   52,   82,  146,  153,  162,  270,  281,  305,  908,  933,
       1224, 1373, 1562, 1569, 1670, 1779])

In [59]:
for i in range(u.size):
    shuffled_indices = rng.permutation(np.flatnonzero(inv == i))
    fold_indices = np.arange(shuffled_indices.size) % n_splits
    for k in np.unique(fold_indices):
        mask = fold_indices == k
        break
    break

In [61]:
shuffled_indices[~mask]

array([1444, 1443, 1445, 1385, 1457, 1394, 1392, 1389, 1519, 1458, 1472,
       1481, 1422, 1490, 1529, 1413, 1400, 1528, 1425, 1440, 1426, 1401,
       1515, 1521, 1393, 1397, 1408, 1533, 1404, 1462, 1387, 1455, 1488,
       1464, 1470, 1453, 1506, 1474, 1439, 1420, 1388, 1477, 1416, 1384,
       1504, 1486, 1483, 1428, 1451, 1427, 1405, 1467, 1386, 1414, 1525,
       1410, 1402, 1429, 1436, 1489, 1485, 1503, 1419, 1505, 1450, 1461,
       1456, 1446, 1484, 1415, 1526, 1399, 1459, 1468, 1517, 1452, 1395,
       1390, 1465, 1478, 1448, 1417, 1396, 1511, 1524, 1434, 1447, 1479,
       1449, 1411, 1527, 1432, 1494, 1398, 1380, 1476, 1510, 1499, 1466,
       1522, 1493, 1502, 1498, 1512, 1460, 1435, 1518, 1480, 1516, 1381,
       1418, 1391, 1431, 1437, 1509, 1514, 1492, 1497, 1438, 1430, 1532,
       1482, 1382, 1495, 1520, 1406, 1508, 1471, 1507, 1454, 1409, 1463,
       1423, 1487, 1530, 1513, 1441, 1424])

In [58]:
for j in np.unique(fold_indices)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.arange(shuffled_indices.size) % n_splits

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
       4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5,
       6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7,
       8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
       0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3])

In [ ]:
indices

In [43]:
np.arange(np.flatnonzero(mask).size) % 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
       4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7])

In [31]:
u

array([  50,   52,   82,  146,  153,  162,  270,  281,  305,  908,  933,
       1224, 1373, 1562, 1569, 1670, 1779])

In [ ]:
import pandas as pd
from itertools import count


input_train='./aozora_datasets_min/train_author_novel.csv'
df_train = pd.read_csv(input_train)

In [ ]:
rarewords

In [ ]:
def remove_maybe_replace_rarewords(corpus, rarewords, token='<UNK>', probability=0.05):
    implies = dict.fromkeys(rarewords, True).get
    subcorpus = [list(filter(implies, doc)) for doc in corpus]
    adj_factor = len(corpus) / sum(map(any, subcorpus)) / 2
    for doc, subdoc in zip(corpus, subcorpus):
        if subdoc and np.random.random() < probability * adj_factor:
            rareword = np.random.choice(subdoc)
            replace = lambda word: {rareword: token}.get(word, word)
            doc = map(replace, doc)
        yield list(filterfalse(implies, doc))
