In [18]:
import numpy as np

X = np.array([[3,3],[3,3],[3,3]])
X, X.shape

(array([[3, 3],
        [3, 3],
        [3, 3]]), (3, 2))

In [20]:
Y = np.array([[4]*4, [5]*4, [6]*4]).reshape(3, 4)
Y, Y.shape

(array([[4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6]]), (3, 4))

In [22]:
XY_1 = np.einsum('ij,ik->ijk', X,Y)
XY_1, XY_1.shape

(array([[[12, 12, 12, 12],
         [12, 12, 12, 12]],
 
        [[15, 15, 15, 15],
         [15, 15, 15, 15]],
 
        [[18, 18, 18, 18],
         [18, 18, 18, 18]]]), (3, 2, 4))

In [25]:
XY_2 = np.einsum('ij,ik->ikj', X,Y)
XY_2, XY_2.shape

(array([[[12, 12],
         [12, 12],
         [12, 12],
         [12, 12]],
 
        [[15, 15],
         [15, 15],
         [15, 15],
         [15, 15]],
 
        [[18, 18],
         [18, 18],
         [18, 18],
         [18, 18]]]), (3, 4, 2))

In [26]:
XY = np.einsum('ij,ik->ik', X,Y)
XY, XY.shape

(array([[24, 24, 24, 24],
        [30, 30, 30, 30],
        [36, 36, 36, 36]]), (3, 4))

In [28]:
XY = np.einsum('ij,ik->i', X,Y)
XY, XY.shape

(array([ 96, 120, 144]), (3,))