In [8]:
import numpy as np
from itertools import count
from scipy.sparse import csr_matrix

In [25]:
def label_encode(x):
    assert x.ndim == 1
    classes, encoded = np.unique(x, return_inverse=True)
    encoder = dict(zip(classes, count()))
    decoder = dict(enumerate(classes))
    return encoded, encoder, decoder

def onehot_encode(x):
    assert x.ndim == 1
    assert np.issubdtype(x.dtype, int)
    data = np.ones_like(x)
    indices = x
    indptr = np.arange(x.size + 1)
    return csr_matrix((data, indices, indptr), dtype=x.dtype).toarray()

In [26]:
y = ['a','a','b','c']

In [27]:
label_encode(np.array(y))

(array([0, 0, 1, 2]), {'a': 0, 'b': 1, 'c': 2}, {0: 'a', 1: 'b', 2: 'c'})

In [29]:
np.unique(y, return_inverse=True)

(array(['a', 'b', 'c'], dtype='<U1'), array([0, 0, 1, 2]))

In [32]:
onehot_encode(label_encode(np.array(y))[0])

/home/ubuntu/anaconda3/envs/data_sci/lib/python3.7/site-packages/ipykernel_launcher.py:10: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  # Remove the CWD from sys.path while we load stuff.


array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [34]:
np.ones_like(label_encode(np.array(y))[0])

array([1, 1, 1, 1])